### ISSUE TITLE
Add `poetry check --lock` as a CI

### ISSUE THREAD

**Issue by Purg** [XAITK/xaitk-saliency#135]
The intention would be to ensure that a branch does not update the content of the pyproject.toml file without appropriately updating the lock file.

**Comment by brianhhu** [comment]
@Purg Is this something that would be more broadly applicable to different repos (not just `xaitk-saliency`) and have we run into issues with diverging pyproject.toml/lock files?

**Comment by Purg** [comment]
I forgot I created this issue! Yes, I would say this is broadly applicable of a check for anything that makes use of poetry. Of course, poetry versions have been released since this was created, so the command is apparently now `poetry check --lock`.

**Comment by bjrichardwebster** [comment]
Part of #159.
