### ISSUE TITLE
Naming of files and classes in xaitk-saliency

### ISSUE THREAD

**Issue by brianhhu** [XAITK/xaitk-saliency#39]
I went through the `xaitk-saliency` package at a high-level and noticed some inconsistencies in our current naming scheme. I don't think any of these are huge issues, but it might help a new user or contributor to have a consistent naming pattern. Here are some examples:

`xaitk-saliency/xaitk-saliency/interfaces`:
- Should the filename represent a shortened version of the class name?
- e.g. `gen_classifier_conf_sal.py` (`GenerateClassifierConfidenceSaliency`) vs. `gen_detection_sal.py` (`GenerateDetectorProposalSaliency`) and `gen_similarity_sal.py` (`GenerateDescriptorSimilaritySaliency`)
- Should these be something like `gen_detector_prop_sal.py` and `gen_descriptor_sim_sal.py`, respectively?

`xaitk-saliency/xaitk-saliency/impls`:
- *Note*: implementation folder names might need to be changed if we decide to make edits to the interface names above.
- Should we use underscores for filenames and Camel case for class names? Again, how closely should the filename match the class name?
- `gen_classifier_conf_sal`: `occlusion.py` vs. `rise_scoring.py`, should this be `occlusion_scoring.py`?
- `gen_similarity_sal`: currently `similarityscoring.py`, should this be `similarity_scoring.py`?

**Comment by Purg** [comment]
Good question, I didn't think about module naming. Consistency is important.

> Should the filename represent a shortened version of the class name?

In general module, names are supposed to represent what they contain, and in the interface cases all that is usually contained is the interface class it self, so I was thinking/assuming that module names *are* shorted versions of the interface class names. Specifically *how* to generate that name I don't think I have any specific rule in mind.

> Should these be something like `gen_detector_prop_sal.py` and `gen_descriptor_sim_sal.py`, respectively?

I think these are good suggestions that seem to follow a similar level of detail to the classifier variant.
I can put up a PR soon-ish with this application.
I thing to be wary of is to avoid too much [bikeshedding](https://thedecisionlab.com/biases/bikeshedding/), which can easily crop up with naming things.

> Note: implementation folder names might need to be changed if we decide to make edits to the interface names above.

Yep.
I thing that is also assumed and not mentioned is the observed pattern in how the implementation submodule matches the interface class module.
I previously thought this would be an obvious observation, but if that's not the case then we can document this.
Of course, this doesn't *have* to be the case for functionality: all that is truly important is the plugin exposure in the ``pyproject.toml``'s ``[tool.poetry.plugins."smqtk_plugins"]`` section.
This assumed "rule" was more for intuitive organization.

> Should we use underscores for filenames and Camel case for class names?

This was assumed as it is part of Python's PEP8 style-guide base.

> Again, how closely should the filename match the class name?

For me it's the same as above: whatever gets across what's contained in the module.
You again have some salient points about consistency, though, that is more important to me than specifically the names.
